todo/board/urls.py
from . import views
from django.conf.urls import url

app_name = 'board'

urlpatterns = [
    url(r'^$', views.Todo_board.as_view(), name='board'),
    url(r'^insert/$', views.check_post, name='board_insert'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.Board_detail.as_view(), name='board_detail'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.Board_update.as_view(), name='board_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.Board_delete.as_view(), name='board_delete'),
    url(r'^update_complete/$', views.update_complete, name='update_complete'),
]

todo/main/urls.py
from . import views
from django.conf.urls import url

app_name = 'main'

urlpatterns = [
    url(r'^$', views.Todo_main.as_view(), name='main'),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # main app
    path('', include('main.urls')),

    # board app
    path('board/', include('board.urls')),
]

todo/board/models.py
from django.db import models

# Create your models here.

class ProjectCode(models.Model):
    pcode = models.CharField(db_column='PCODE', primary_key=True, max_length=4)  # Field name made lowercase.
    pname = models.CharField(db_column='PNAME', max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'project_code'


class TodoList(models.Model):
    no = models.AutoField(db_column='NO', primary_key=True)  # Field name made lowercase.
    pcode = models.CharField(db_column='PCODE', max_length=4)  # Field name made lowercase.
    user_id = models.CharField(db_column='USER_ID', max_length=50, blank=True, null=True)  # Field name made lowercase.
    title = models.CharField(db_column='TITLE', max_length=200, blank=True, null=True)  # Field name made lowercase.
    content = models.CharField(db_column='CONTENT', max_length=1000, blank=True, null=True)  # Field name made lowercase.
    is_complete = models.IntegerField(db_column='IS_COMPLETE', blank=True, null=True)  # Field name made lowercase.
    priority = models.IntegerField(db_column='PRIORITY', blank=True, null=True)  # Field name made lowercase.
    end_date = models.DateField(db_column='END_DATE', blank=True, null=True)  # Field name made lowercase.

    def todo_save(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'todo_list'

todo/main/models.py
from django.db import models

# Create your models here.

todo/board/forms.py
from django import forms
from .models import TodoList


class DateInput(forms.DateInput):
    input_type = 'date'


class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('title', 'content', 'end_date', 'is_complete')
        widgets = {
            'end_date': DateInput()
        }

todo/board/views.py
from django.shortcuts import render
from django.views import generic

from board.forms import TodoForm
from board.models import TodoList
from datetime import datetime

from django.http import JsonResponse


class Todo_board(generic.TemplateView):
    # get 방식으로 받았을 때, index.html로 이동
    def get(self, request, *args, **kwargs):
        template_name = 'board/todo_list.html'
        # 기한 없는 일정, 마감 x
        todo_list_no_end_date = TodoList.objects.all() \
            .filter(end_date__isnull=True, is_complete=0) \
            .order_by('priority')
        # 기한 있고, 마감 x
        todo_list_end_date_non_complete = TodoList.objects.all() \
            .filter(end_date__isnull=False, is_complete=0) \
            .order_by('priority')
        # 마감
        todo_list_end_date_complete = TodoList.objects.all() \
            .filter(is_complete=1) \
            .order_by('end_date')
        today = datetime.now()

        # end_date가 가까움
        close_end_day = []
        # end_date가 이미 지남
        over_end_day = []

        # 기한이 있는데 마감이 안된 것들 중
        for i in todo_list_end_date_non_complete:
            e_day = str(i.end_date).split("-")
            end_day = datetime(int(e_day[0]), int(e_day[1]), int(e_day[2]))
            if (end_day - today).days < -1:
                over_end_day.append(i.title)
            if -1 <= (end_day - today).days < 3:
                close_end_day.append(i.title)

        return render(request, template_name, {"todo_list_endDate_non_complete": todo_list_end_date_non_complete,
                                               "todo_list_endDate_complete": todo_list_end_date_complete,
                                               "todo_list_no_endDate": todo_list_no_end_date,
                                               'close_end_day': close_end_day, 'over_end_day': over_end_day})


def check_post(request):
    template_name = 'board/succeed.html'

    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            message = "일정을 추가하였습니다."
            todo = form.save(commit=False)
            todo.todo_save()
            return render(request, template_name, {"message": message})
    template_name = 'board/insert.html'
    form = TodoForm(initial={"is_complete": 0})
    return render(request, template_name, {"form": form})


class Board_detail(generic.DetailView):
    model = TodoList
    template_name = 'board/board_detail.html'
    context_object_name = 'todo'


class Board_update(generic.UpdateView):
    model = TodoList
    fields = ('title', 'content', 'end_date')
    template_name = 'board/board_update.html'
    success_url = '/board/'

    def form_valid(self, form):
        form.save()
        return render(self.request, 'board/succeed.html', {"message": "일정을 업데이트 했습니다"})

    # 상세보기 -> 수정버튼 눌렀을 때 기존에 작성한 내용이 적용되어야함
    def get(self, request, *args, **kwargs):
        # 오브젝트를 받아와서 폼 클래스를 받아온 후 return
        self.object = self.get_object()
        form = self.get_form(TodoForm)

        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)


class Board_delete(generic.DeleteView):
    model = TodoList
    success_url = '/board/'
    context_object_name = 'todo'


def update_complete(request):
    if request.method == 'POST':
        pk = request.POST.get('pk')
        is_complete = request.POST.get('is_complete')

        try:
            todo_item = TodoList.objects.get(no=pk)
            todo_item.is_complete = True if is_complete == 'true' else False
            todo_item.save()

            return JsonResponse({'success': True})
        except TodoList.DoesNotExist:
            return JsonResponse({'success': False, 'error': '일정을 찾을 수 없습니다.'})

    return JsonResponse({'success': False, 'error': '올바른 요청이 아닙니다.'})

todo/main/views.py
from django.shortcuts import render
from django.views import generic


class Todo_main(generic.TemplateView):
    # get 방식으로 받았을 때, index.html로 이동
    def get(self, request, *args, **kwargs):
        template_name = 'main/index.html'
        return render(request, template_name)

todo/board/templates/board/board_detail.html
{%  extends 'main/common/header.html' %} <!-- header.html을 상속하겠다 -->
{% block main %}
	<div class="container text-center pt-5">
		<h1>{{ todo.title }}</h1>

		<br>
		<table class="table table-bordered">
            {% if todo.is_complete == true %}
			<TR>
				<TH>DONE</TH>
				<TD>N</TD>
			</TR>
            {% else %}
			<TR>
				<TH>DONE</TH>
				<TD>Y</TD>
			</TR>
            {% endif %}
			<TR>
				<TH>due date</TH>
				<TD>{{ todo.end_date }}</TD>
			</TR>
			<TR>
				<TH>CONTENT</TH>
				<TD COLSPAN=3>{{ todo.content }}</TD>
			</TR>
		</TABLE>
{#		<a href="complete?num=${ todo.num }">완료</a>&nbsp;&nbsp;#}
		<a href="{% url 'board:board_update' pk=todo.no %}">수정하기</a>&nbsp;&nbsp;
		<a href="{% url 'board:board_delete' pk=todo.no %}">삭제하기</a>&nbsp;&nbsp;
		<a href="{% url 'board:board' %}">초기화면</a>
		 <br> <br>
	</div>
{% endblock main %}

todo/board/templates/board/board_update.html
{%  extends 'main/common/header.html' %} <!-- header.html을 상속하겠다 -->
{% block main %}
    <div class="container text-center pt-5">
		<h1>할 일 수정</h1>
		<form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}

			<button type="submit" class="btn btn-info">Submit</button>
		</form>
		<a href="{% url 'board:board' %}">전체화면</a>
		<br>
		<br>
	</div>
{% endblock main %}

todo/board/templates/board/insert.html
{%  extends 'main/common/header.html' %} <!-- header.html을 상속하겠다 -->
{% block main %}
    <div class="container text-center pt-5">
		<h1>할 일 추가</h1>
        <br>
		<form method="POST" class="post-form" action="{%  url 'board:board_insert' %}">
            {% csrf_token %}
            <div class="row">
				<div class="form-group text-left col-sm-8">
					<label for="title">제목</label> <input type="text"
						class="form-control" name="title" value="{{ form.title.value|default_if_none:'' }}">
				</div>
				<div class="form-group text-left col-sm-4">
					<label for="end_date">종료 날짜 : </label> <input type="date"
						class="form-control" name="end_date" value="{{ form.end_date.value|default_if_none:'' }}">
				</div>
			</div>
            <div class="form-group text-left">
                <label for="content">내 용:</label>
                <textarea class="form-control" rows="2" id="content" name="content" value="{{ form.content.value|default_if_none:'' }}"></textarea>
            </div>
            <div class="form-group text-left" style="display: none">
                <input type="number"
						class="form-control" name="is_complete" value="{{ form.is_complete.value|default_if_none:0 }}">
            </div>
            <br>
			<button type="submit" class="btn btn-info">Submit</button>
		</form>
        <br>
		<a href="{%  url 'board:board' %}">리스트 화면</a>
		<br>
		<br>
	</div>
{% endblock main %}

todo/board/templates/board/succeed.html
<script>
    message = "{{ message }}"
    console.log(message);
    alert(message);
    window.location.href = "{% url 'board:board' %}"
</script>

todo/board/templates/board/todo_list.html
{% extends 'main/common/header.html' %}
{% block main %}
<style>
.dragging {
    z-index: 9999;  // 드래그 중인 항목의 z-index 값을 큰 값으로 설정
}

.list-group {
    height: 100vh;
}

.title{
    font-weight: bold;
    font-size: 1.3em;
    margin-bottom: 0.7rem;
}

.list-group-item:hover {
    filter: brightness(90%);
}

</style>

<script>
function moveToDetail(element) {
    window.location.href = element.getAttribute("data-url");
}
</script>

<div class="container text-center pt-5">
    <h1>오늘 할 일</h1>
    <div class="text-right mb-2">
        <div class="btn-group">
            <a type="button" href="{% url 'board:board_insert' %}" class="btn btn-info" role="button">할 일 추가</a>
        </div>
    </div>
    <br>


{#    {% if over_end_day %}#}
{#    <div class="alert alert-info">#}
{#        <strong>마감이 지난 일정!</strong> {{ over_end_day }}#}
{#    </div>#}
{#    {% endif %}#}
{#    {% if close_end_day %}#}
{#    <div class="alert alert-info">#}
{#        <strong>마감이 가까운 일정!</strong> {{ close_end_day }}#}
{#    </div>#}
{#    {% endif %}#}

    <br>
    <div class="row">
        <div class="col-md-4">
            <div class="container">
                <h2>기한 있는 일정</h2><br>
                <div id="todo_list_endDate" class="list-group col">
                    {% for list in todo_list_endDate_non_complete %}
                    <div class="list-group-item" div_pk="{{ list.no }}" onclick="moveToDetail(this)" data-url="{% url 'board:board_detail' pk=list.no %}">
                        <div class="title">{{ list.title }}</div>
                        <p>{{ list.end_date }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="container">
                <h2>기한 없는 일정</h2><br>
                <div id="todo_list_no_endDate" class="list-group col">
                    {% with end_date="마감일 없음" %}
                    {% for list in todo_list_no_endDate %}
                    <div class="list-group-item" div_pk="{{ list.no }}" onclick="moveToDetail(this)" data-url="{% url 'board:board_detail' pk=list.no %}">
                        <div class="title">{{ list.title }}</div>
                        <p>{{ end_date }}</p>
                    </div>
                    {% endfor %}
                    {% endwith %}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="container">
                <h2>마감된 일정</h2><br>
                <div class="list-group col" id="completed_list">
                    {% with end_date="마감일 없음" %}
                    {% for list in todo_list_endDate_complete %}
                    {% if list.end_date == None %}
                    <div class="list-group-item list-group-item-success" div_pk="{{ list.no }}" onclick="moveToDetail(this)" data-url="{% url 'board:board_detail' pk=list.no %}">
                        <div class="title">{{ list.title }}</div>
                        <p>{{ end_date }}</p>
                    </div>
                    {% else %}
                    <div class="list-group-item list-group-item-success" div_pk="{{ list.no }}" onclick="moveToDetail(this)" data-url="{% url 'board:board_detail' pk=list.no %}">
                        <div class="title">{{ list.title }}</div>
                        <p>{{ list.end_date }}</p>
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
</div>

<script  src="https://code.jquery.com/jquery-latest.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>

<script>
    $(function() {
        // draggable 및 droppable 설정 함수
         function makeDraggableAndDroppable(draggable_element, droppable_element, isCompleted) {
            draggable_element.draggable({
                revert: "invalid",
                helper: "original",
                start: function(event, ui) {
                    $(this).addClass("dragging"); // 드래그 시작 시 'dragging' 클래스 추가
                },
                stop: function(event, ui) {
                    $(this).removeClass("dragging"); // 드래그 종료 시 'dragging' 클래스 제거
                }
            });

            droppable_element.droppable({
                accept: ".list-group-item",
                drop: function(event, ui) {
                    let droppedItem = ui.helper;
                    let originalItem = ui.draggable;

                    // 드롭한 아이템의 내용
                    let content = droppedItem.html();
                    let data_url = originalItem.attr("data-url");

                    if (isCompleted) {
                        // 마감된 일정에 추가
                        let newElement = $("<div class='list-group-item list-group-item-success' div_pk='" + originalItem.attr("div_pk") + "'>" + content + "</div>");
                        newElement.attr("onclick", "moveToDetail(this)");
                        newElement.attr("data-url", data_url);

                        $("#completed_list").append(newElement);
                       makeDraggableAndDroppable($("#completed_list .list-group-item"), $("#completed_list"), true);
                    } else {
                        // 마감일이 있는 경우
                        if (originalItem.find("p").text() !== "마감일 없음") {
                            // 드롭한 아이템을 기한 있는 일정 목록에 추가
                            let newElement = $("<div class='list-group-item' div_pk='" + originalItem.attr("div_pk") + "'>" + content + "</div>");
                            newElement.attr("onclick", "moveToDetail(this)");
                            newElement.attr("data-url", data_url);

                            $("#todo_list_endDate").append(newElement);
                            makeDraggableAndDroppable($("#todo_list_endDate .list-group-item"), $("#todo_list_endDate"), false);
                        } else {
                            // 드롭한 아이템을 기한 없는 일정 목록에 추가
                            let newElement = $("<div class='list-group-item' div_pk='" + originalItem.attr("div_pk") + "'>" + content + "</div>");
                            newElement.attr("onclick", "moveToDetail(this)");
                            newElement.attr("data-url", data_url);

                            $("#todo_list_no_endDate").append(newElement);
                            makeDraggableAndDroppable($("#todo_list_no_endDate .list-group-item"), $("#todo_list_no_endDate"), false);
                        }
                    }

                    // 드래그한 아이템의 원래 위치에서 삭제
                    originalItem.remove();

                    // is_complete 값을 변경하고 저장
                    let pk = originalItem.attr("div_pk");
                    console.log(isCompleted)
                    updateComplete(pk, isCompleted);
                }
            }).draggable({
                revert: "invalid",
                helper: "original",
                start: function(event, ui) {
                    $(this).addClass("dragging"); // 드래그 시작 시 'dragging' 클래스 추가
                },
                stop: function(event, ui) {
                    $(this).removeClass("dragging"); // 드래그 종료 시 'dragging' 클래스 제거
                }
            });
        }

        // 기한 있는 일정에서 drag 가능하도록 설정
        makeDraggableAndDroppable($("#todo_list_endDate .list-group-item"), $("#todo_list_endDate"), false);

        // 기한 없는 일정에서 drag 가능하도록 설정
        makeDraggableAndDroppable($("#todo_list_no_endDate .list-group-item"), $("#todo_list_no_endDate"), false);

        // 마감된 일정에서 drag 가능하도록 설정
        makeDraggableAndDroppable($("#completed_list .list-group-item"), $("#completed_list"), true);

        // is_complete 값을 변경하고 저장하는 함수
        function updateComplete(pk, isComplete) {
            $.ajax({
                type: "POST",
                url: "{% url 'board:update_complete' %}",
                data: {
                    pk: pk,
                    is_complete: isComplete,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response) {
                    console.log("is_complete updated to " + isComplete);
                },
                error: function(xhr, errmsg, err) {
                    console.log("Failed to update is_complete");
                }
            });
        }
    });
</script>

{% endblock main %}

todo/board/templates/board/todolist_confirm_delete.html
<style>
* {box-sizing: border-box;}

/* Set a style for all buttons */
button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Float cancel and delete buttons and add an equal width */
.cancelbtn, .deletebtn {
  float: left;
  width: 50%;
}

/* Add a color to the cancel button */
.cancelbtn {
  background-color: #ccc;
  color: black;
}

/* Add a color to the delete button */
.deletebtn {
  background-color: #17a1b8;
}

/* Add padding and center-align text to the container */
.container {
  padding: 16px;
  text-align: center;
}

/* The Modal (background) */
.modal {
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: #474e5d;
  padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    padding: 2% 5% 1% 5%;
  border: 1px solid #888;
  width: 40%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* The Modal Close Button (x) */
.close {
  position: absolute;
  right: 35px;
  top: 15px;
  font-size: 40px;
  font-weight: bold;
  color: #f1f1f1;
}

.close:hover,
.close:focus {
  color: #f44336;
  cursor: pointer;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and delete button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .deletebtn {
     width: 100%;
  }
}
</style>

<div id="id01" class="modal">
  <span onclick="window.location.href='/board/{{ todo.no }}/detail'" class="close" title="Close Modal">&times;</span>
   <form method="POST" class="post-form modal-content">
    <div class="container">
       {%csrf_token%}
       <p>정말로 "{{ todo.title }}" 일정을 삭제하시나요?</p>

      <div class="clearfix">
        <button type="button" class="cancelbtn">Cancel</button>
        <button type="submit" class="save btn btn-default deletebtn" value="confirm">Delete</button>
      </div>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target === modal) {
    window.location.href='/board/{{ todo.no }}/detail'
  }
}
</script>

todo/main/templates/main/common/header.html
<!DOCTYPE html>
<html>
<head>
    <title>TodoList</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script
        src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'main:main' %}">TodoList</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navb" aria-controls="navb" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
		<div class="collapse navbar-collapse" id="navb">
			<ul class="navbar-nav mr-auto">
              <li class="nav-item"><a href="{% url 'board:board' %}">today list</a></li>
			</ul>
{#			<jsp:include page="loginCheck.jsp"></jsp:include>#}
		</div>
	</nav>

    {% block main %} <!-- 상속받은 자식 템플릿이 구현해줄것임 -->

    {% endblock main %}
</body>
</html>

todo/main/templates/main/index.html
{%  extends 'main/common/header.html' %} <!-- header.html을 상속하겠다 -->
{% block main %}
	<div class="container text-center pt-5">
		<h1>TodoList Main Page</h1>
	</div>
{% endblock main %}